package com.wso2.support;

/**
 * Query need to entire migration define as constants
 */
public class MigrationClientConstant {

    /**
     * REGISTRY TABLES
     */
    public static String INSERT_REG_CLUSTER_LOCK = "INSERT INTO REG_CLUSTER_LOCK (REG_LOCK_NAME, REG_LOCK_STATUS, " +
            "REG_LOCKED_TIME, REG_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_REG_LOG = "INSERT INTO REG_LOG (REG_LOG_ID, REG_PATH, REG_USER_ID, REG_LOGGED_TIME, " +
            "REG_ACTION, REG_ACTION_DATA, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?, ?)";

    public static String INSERT_REG_PATH = "INSERT INTO REG_PATH (REG_PATH_ID, REG_PATH_VALUE, REG_PATH_PARENT_ID, " +
            "REG_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_REG_CONTENT = "INSERT INTO REG_CONTENT (REG_CONTENT_ID, REG_CONTENT_DATA, " +
            "REG_TENANT_ID) VALUES (?, ?, ?)";

    public static String INSERT_REG_CONTENT_HISTORY = "INSERT INTO REG_CONTENT_HISTORY (REG_CONTENT_ID, " +
            "REG_CONTENT_DATA, REG_DELETED, REG_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_REG_RESOURCE = "INSERT INTO REG_RESOURCE (REG_PATH_ID, REG_NAME, REG_VERSION, " +
            "REG_MEDIA_TYPE, REG_CREATOR, REG_CREATED_TIME, REG_LAST_UPDATOR, REG_LAST_UPDATED_TIME, REG_DESCRIPTION," +
            " REG_CONTENT_ID, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    public static String INSERT_REG_RESOURCE_HISTORY = "INSERT INTO REG_RESOURCE_HISTORY (REG_PATH_ID, REG_NAME, " +
            "REG_VERSION, REG_MEDIA_TYPE, REG_CREATOR, REG_CREATED_TIME, REG_LAST_UPDATOR, REG_LAST_UPDATED_TIME, " +
            "REG_DESCRIPTION, REG_CONTENT_ID, REG_DELETED, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

    public static String INSERT_REG_COMMENT = "INSERT INTO REG_COMMENT (REG_ID, REG_COMMENT_TEXT, REG_USER_ID, " +
            "REG_COMMENTED_TIME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_RESOURCE_COMMENT = "INSERT INTO REG_RESOURCE_COMMENT (REG_COMMENT_ID, REG_VERSION, " +
            "REG_PATH_ID, REG_RESOURCE_NAME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_RATING = "INSERT INTO REG_RATING (REG_ID, REG_RATING, REG_USER_ID, " +
            "REG_RATED_TIME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_RESOURCE_RATING = "INSERT INTO REG_RESOURCE_RATING (REG_RATING_ID, REG_VERSION, " +
            "REG_PATH_ID, REG_RESOURCE_NAME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_TAG = "INSERT INTO REG_TAG (REG_ID, REG_TAG_NAME, REG_USER_ID, REG_TAGGED_TIME, " +
            "REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_RESOURCE_TAG = "INSERT INTO REG_RESOURCE_TAG (REG_TAG_ID, REG_VERSION, " +
            "REG_PATH_ID, REG_RESOURCE_NAME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_PROPERTY = "INSERT INTO REG_PROPERTY (REG_ID, REG_NAME, REG_VALUE, REG_TENANT_ID)" +
            " VALUES (?, ?, ?, ?) ";

    public static String INSERT_REG_RESOURCE_PROPERTY = "INSERT INTO REG_RESOURCE_PROPERTY (REG_PROPERTY_ID, " +
            "REG_VERSION, REG_PATH_ID, REG_RESOURCE_NAME, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_ASSOCIATION = "INSERT INTO REG_ASSOCIATION (REG_ASSOCIATION_ID, REG_SOURCEPATH, " +
            "REG_TARGETPATH, REG_ASSOCIATION_TYPE, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_REG_SNAPSHOT = "INSERT INTO REG_SNAPSHOT (REG_SNAPSHOT_ID, REG_PATH_ID, " +
            "REG_RESOURCE_NAME, REG_RESOURCE_VIDS, REG_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String SELECT_REG_CLUSTER_LOCK = "SELECT REG_LOCK_NAME, REG_LOCK_STATUS, REG_LOCKED_TIME, " +
            "REG_TENANT_ID FROM REG_CLUSTER_LOCK";

    public static String SELECT_REG_LOG = "SELECT REG_LOG_ID, REG_PATH, REG_USER_ID, REG_LOGGED_TIME, REG_ACTION, " +
            "REG_ACTION_DATA, REG_TENANT_ID FROM REG_LOG";

    public static String SELECT_REG_PATH = "SELECT REG_PATH_ID, REG_PATH_VALUE, REG_PATH_PARENT_ID, REG_TENANT_ID " +
            "FROM REG_PATH";

    public static String SELECT_REG_CONTENT = "SELECT REG_CONTENT_ID, REG_CONTENT_DATA, REG_TENANT_ID FROM REG_CONTENT";

    public static String SELECT_REG_CONTENT_HISTORY = "SELECT REG_CONTENT_ID, REG_CONTENT_DATA, REG_DELETED, " +
            "REG_TENANT_ID FROM REG_CONTENT_HISTORY";

    public static String SELECT_REG_RESOURCE = "SELECT REG_PATH_ID, REG_NAME, REG_VERSION, REG_MEDIA_TYPE, " +
            "REG_CREATOR, REG_CREATED_TIME, REG_LAST_UPDATOR, REG_LAST_UPDATED_TIME, REG_DESCRIPTION, REG_CONTENT_ID," +
            " REG_TENANT_ID FROM REG_RESOURCE";

    public static String SELECT_REG_RESOURCE_HISTORY = "SELECT REG_PATH_ID, REG_NAME, REG_VERSION, REG_MEDIA_TYPE, " +
            "REG_CREATOR, REG_CREATED_TIME, REG_LAST_UPDATOR, REG_LAST_UPDATED_TIME, REG_DESCRIPTION, REG_CONTENT_ID," +
            " REG_DELETED, REG_TENANT_ID FROM REG_RESOURCE_HISTORY";

    public static String SELECT_REG_COMMENT = "SELECT REG_ID, REG_COMMENT_TEXT, REG_USER_ID, REG_COMMENTED_TIME, " +
            "REG_TENANT_ID FROM REG_COMMENT";

    public static String SELECT_REG_RESOURCE_COMMENT = "SELECT REG_COMMENT_ID, REG_VERSION, REG_PATH_ID, " +
            "REG_RESOURCE_NAME, REG_TENANT_ID FROM REG_RESOURCE_COMMENT";

    public static String SELECT_REG_RATING = "SELECT REG_ID, REG_RATING, REG_USER_ID, REG_RATED_TIME, REG_TENANT_ID " +
            "FROM REG_RATING";

    public static String SELECT_REG_RESOURCE_RATING = "SELECT REG_RATING_ID, REG_VERSION, REG_PATH_ID, " +
            "REG_RESOURCE_NAME, REG_TENANT_ID FROM REG_RESOURCE_RATING";

    public static String SELECT_REG_TAG = "SELECT REG_ID, REG_TAG_NAME, REG_USER_ID, REG_TAGGED_TIME, REG_TENANT_ID " +
            "FROM REG_TAG";

    public static String SELECT_REG_RESOURCE_TAG = "SELECT REG_TAG_ID, REG_VERSION, REG_PATH_ID, REG_RESOURCE_NAME, " +
            "REG_TENANT_ID FROM REG_RESOURCE_TAG";

    public static String SELECT_REG_PROPERTY = "SELECT REG_ID, REG_NAME, REG_VALUE, REG_TENANT_ID FROM REG_PROPERTY";

    public static String SELECT_REG_RESOURCE_PROPERTY = "SELECT REG_PROPERTY_ID, REG_VERSION, REG_PATH_ID, " +
            "REG_RESOURCE_NAME, REG_TENANT_ID FROM REG_RESOURCE_PROPERTY";

    public static String SELECT_REG_ASSOCIATION = "SELECT REG_ASSOCIATION_ID, REG_SOURCEPATH, REG_TARGETPATH, " +
            "REG_ASSOCIATION_TYPE, REG_TENANT_ID FROM REG_ASSOCIATION";

    public static String SELECT_REG_SNAPSHOT = "SELECT REG_SNAPSHOT_ID, REG_PATH_ID, REG_RESOURCE_NAME, " +
            "REG_RESOURCE_VIDS, REG_TENANT_ID FROM REG_SNAPSHOT";

    /**
     * USER MANAGER TABLES
     */
    public static String INSERT_UM_TENANT = "INSERT INTO UM_TENANT (UM_ID, UM_DOMAIN_NAME, UM_EMAIL, UM_ACTIVE, " +
            "UM_CREATED_DATE, UM_USER_CONFIG) VALUES (?, ?, ?, ?, ?, ?)";

    public static String INSERT_UM_USER = "INSERT INTO UM_USER (UM_ID, UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE," +
            " UM_REQUIRE_CHANGE, UM_CHANGED_TIME, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?, ?)";

    public static String INSERT_UM_USER_ATTRIBUTE = "INSERT INTO UM_USER_ATTRIBUTE (UM_ID, UM_ATTR_NAME, " +
            "UM_ATTR_VALUE, UM_PROFILE_ID, UM_USER_ID, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?)";

    public static String INSERT_UM_ROLE = "INSERT INTO UM_ROLE (UM_ID, UM_ROLE_NAME, UM_TENANT_ID) VALUES (?, ?, ?) ";

    public static String INSERT_UM_PERMISSION = "INSERT INTO UM_PERMISSION (UM_ID, UM_RESOURCE_ID, UM_ACTION, " +
            "UM_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_UM_ROLE_PERMISSION = "INSERT INTO  UM_ROLE_PERMISSION (UM_ID, UM_PERMISSION_ID, " +
            "UM_ROLE_NAME, UM_IS_ALLOWED, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?) ";

    public static String INSERT_UM_USER_PERMISSION = "INSERT INTO UM_USER_PERMISSION (UM_ID, UM_PERMISSION_ID, " +
            "UM_USER_NAME, UM_IS_ALLOWED, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?) ";

    public static String INSERT_UM_USER_ROLE = "INSERT INTO UM_USER_ROLE (UM_ID, UM_ROLE_ID, UM_USER_ID, " +
            "UM_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_UM_DIALECT = "INSERT INTO UM_DIALECT (UM_ID, UM_DIALECT_URI, UM_TENANT_ID) VALUES (?," +
            " ?, ?)";

    public static String INSERT_UM_CLAIM = "INSERT INTO UM_CLAIM (UM_ID, UM_DIALECT_ID, UM_CLAIM_URI, UM_DISPLAY_TAG," +
            " UM_DESCRIPTION, UM_MAPPED_ATTRIBUTE, UM_REG_EX, UM_SUPPORTED, UM_REQUIRED, UM_DISPLAY_ORDER, " +
            "UM_TENANT_ID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ";

    public static String INSERT_UM_PROFILE_CONFIG = "INSERT INTO UM_PROFILE_CONFIG (UM_ID, UM_DIALECT_ID, " +
            "UM_PROFILE_NAME, UM_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_UM_CLAIM_BEHAVIOR = "INSERT INTO UM_CLAIM_BEHAVIOR (UM_ID, UM_PROFILE_ID, " +
            "UM_CLAIM_ID, UM_BEHAVIOUR, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?)";

    public static String INSERT_UM_HYBRID_ROLE = "INSERT INTO UM_HYBRID_ROLE (UM_ID, UM_ROLE_NAME, UM_TENANT_ID) " +
            "VALUES (?, ?, ?)";

    public static String INSERT_UM_HYBRID_USER_ROLE = "INSERT INTO UM_HYBRID_USER_ROLE (UM_ID, UM_USER_NAME, " +
            "UM_ROLE_ID, UM_TENANT_ID) VALUES (?, ?, ?, ?)";

    public static String INSERT_UM_HYBRID_REMEMBER_ME = "INSERT INTO UM_HYBRID_REMEMBER_ME (UM_ID, UM_USER_NAME, " +
            "UM_COOKIE_VALUE, UM_CREATED_TIME, UM_TENANT_ID) VALUES (?, ?, ?, ?, ?) ";

    public static String SELECT_UM_TENANT = "SELECT UM_ID, UM_DOMAIN_NAME, UM_EMAIL, UM_ACTIVE, UM_CREATED_DATE, " +
            "UM_USER_CONFIG FROM UM_TENANT";

    public static String SELECT_UM_USER = "SELECT UM_ID, UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, " +
            "UM_REQUIRE_CHANGE, UM_CHANGED_TIME, UM_TENANT_ID FROM UM_USER";

    public static String SELECT_UM_USER_ATTRIBUTE = "SELECT UM_ID, UM_ATTR_NAME, UM_ATTR_VALUE, UM_PROFILE_ID, " +
            "UM_USER_ID, UM_TENANT_ID FROM UM_USER_ATTRIBUTE";

    public static String SELECT_UM_ROLE = "SELECT UM_ID, UM_ROLE_NAME, UM_TENANT_ID FROM UM_ROLE";

    public static String SELECT_UM_PERMISSION = "SELECT UM_ID, UM_RESOURCE_ID, UM_ACTION, UM_TENANT_ID FROM " +
            "UM_PERMISSION";

    public static String SELECT_UM_ROLE_PERMISSION = "SELECT UM_ID, UM_PERMISSION_ID, UM_ROLE_NAME, UM_IS_ALLOWED, " +
            "UM_TENANT_ID FROM UM_ROLE_PERMISSION";

    public static String SELECT_UM_USER_PERMISSION = "SELECT UM_ID, UM_PERMISSION_ID, UM_USER_NAME, UM_IS_ALLOWED, " +
            "UM_TENANT_ID FROM UM_USER_PERMISSION";

    public static String SELECT_UM_USER_ROLE = "SELECT UM_ID, UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID FROM UM_USER_ROLE";

    public static String SELECT_UM_DIALECT = "SELECT UM_ID, UM_DIALECT_URI, UM_TENANT_ID FROM UM_DIALECT";

    public static String SELECT_UM_CLAIM = "SELECT UM_ID, UM_DIALECT_ID, UM_CLAIM_URI, UM_DISPLAY_TAG, " +
            "UM_DESCRIPTION, UM_MAPPED_ATTRIBUTE, UM_REG_EX, UM_SUPPORTED, UM_REQUIRED, UM_DISPLAY_ORDER, " +
            "UM_TENANT_ID FROM UM_CLAIM";

    public static String SELECT_UM_PROFILE_CONFIG = "SELECT UM_ID, UM_DIALECT_ID, UM_PROFILE_NAME, UM_TENANT_ID FROM " +
            "UM_PROFILE_CONFIG";

    public static String SELECT_UM_CLAIM_BEHAVIOR = "SELECT UM_ID, UM_PROFILE_ID, UM_CLAIM_ID, UM_BEHAVIOUR, " +
            "UM_TENANT_ID FROM UM_CLAIM_BEHAVIOR";

    public static String SELECT_UM_HYBRID_ROLE = "SELECT UM_ID, UM_ROLE_NAME, UM_TENANT_ID FROM UM_HYBRID_ROLE";

    public static String SELECT_UM_HYBRID_USER_ROLE = "SELECT UM_ID, UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID FROM " +
            "UM_HYBRID_USER_ROLE";

    public static String SELECT_UM_HYBRID_REMEMBER_ME = "SELECT UM_ID, UM_USER_NAME, UM_COOKIE_VALUE, " +
            "UM_CREATED_TIME, UM_TENANT_ID FROM UM_HYBRID_REMEMBER_ME";
}
